In [1]:
import numpy as np

# Перевірка роботи середовища
a = np.array([1, 2, 3, 4, 5])
print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)

[1 2 3 4 5]
shape: (5,)
dtype: int64


In [2]:
# Дані для Варіанта 4 (Харків)
temps = np.array([-6, -5, 1, 10, 17, 20, 22, 21, 15, 8, 1, -4])
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])
month_numbers = np.arange(1, 13)

print("temps:", temps, "| shape:", temps.shape, "| dtype:", temps.dtype)
print("days_in_month:", days_in_month, "| shape:", days_in_month.shape, "| dtype:", days_in_month.dtype)
print("month_numbers:", month_numbers, "| shape:", month_numbers.shape, "| dtype:", month_numbers.dtype)

temps: [-6 -5  1 10 17 20 22 21 15  8  1 -4] | shape: (12,) | dtype: int64
days_in_month: [31 28 31 30 31 30 31 31 30 31 30 31] | shape: (12,) | dtype: int64
month_numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12] | shape: (12,) | dtype: int64


In [3]:
# 1. Переведення в °F
temps_fahrenheit = temps * 9/5 + 32
print("Температура у °F:", temps_fahrenheit)

# 2. Кількість днів у році тепліше 15°C
warm_days_total = days_in_month[temps > 15].sum()
print("Всього днів у році тепліше 15°C:", warm_days_total)

# 3. Перевірка загальної кількості днів у році
print("Сума днів у році:", days_in_month.sum())

Температура у °F: [21.2 23.  33.8 50.  62.6 68.  71.6 69.8 59.  46.4 33.8 24.8]
Всього днів у році тепліше 15°C: 123
Сума днів у році: 365


In [4]:
# 1. Найтепліший та найхолодніший місяць
max_temp = temps.max()
max_month_idx = temps.argmax()  # Індекс (0-11)

min_temp = temps.min()
min_month_idx = temps.argmin()  # Індекс (0-11)

print(f"Найтепліший місяць: {month_numbers[max_month_idx]}-й (температура: {max_temp}°C, індекс: {max_month_idx})")
print(f"Найхолодніший місяць: {month_numbers[min_month_idx]}-й (температура: {min_temp}°C, індекс: {min_month_idx})")

# 2. Номери місяців з температурою нижче 0°C
freezing_months = month_numbers[temps < 0]
print("Місяці з температурою нижче 0°C:", freezing_months)

# 3. Сортування без зміни оригіналу
sorted_temps = np.sort(temps)
print("Відсортовані температури:", sorted_temps)
print("Оригінальний масив temps не змінився:", temps)

Найтепліший місяць: 7-й (температура: 22°C, індекс: 6)
Найхолодніший місяць: 1-й (температура: -6°C, індекс: 0)
Місяці з температурою нижче 0°C: [ 1  2 12]
Відсортовані температури: [-6 -5 -4  1  1  8 10 15 17 20 21 22]
Оригінальний масив temps не змінився: [-6 -5  1 10 17 20 22 21 15  8  1 -4]


In [5]:
# 1. Створення 3-го рядка (сонячні години за місяць для Харкова) та об'єднання в масив (3, 12)
sun_hours = np.array([50, 70, 120, 170, 240, 270, 290, 260, 190, 120, 50, 40])
matrix_3d = np.array([temps, days_in_month, sun_hours])

print("Форма матриці:", matrix_3d.shape)

# 2. Сума та середнє по кожному рядку (axis=1)
row_sums = matrix_3d.sum(axis=1)
row_means = matrix_3d.mean(axis=1)

print("Сума по рядках [temps, days, sun]:", row_sums)
print("Середнє по рядках [temps, days, sun]:", row_means)

# 3. Сума по стовпцях (axis=0)
col_sums = matrix_3d.sum(axis=0)
print("Сума по стовпцях (кожен місяць):", col_sums)
print("Сума для першого стовпця (Січень):", col_sums[0])

Форма матриці: (3, 12)
Сума по рядках [temps, days, sun]: [ 100  365 1870]
Середнє по рядках [temps, days, sun]: [  8.33333333  30.41666667 155.83333333]
Сума по стовпцях (кожен місяць): [ 75  93 152 210 288 320 343 312 235 159  81  67]
Сума для першого стовпця (Січень): 75


In [6]:
# 1. Двовимірний масив rows (2, 12)
rows = np.array([temps, days_in_month])
correction = np.array([1, 0])

# 2. Демонстрація помилки (розкоментуйте, щоб побачити ValueError):
# rows + correction 
# Помилка: ValueError: operands could not be broadcast together with shapes (2,12) (2,)

# 3. Виправлення через reshape
correction_reshaped = correction.reshape(2, 1)
result = rows + correction_reshaped

print("Результат після reshape:\n", result)

Результат після reshape:
 [[-5 -4  2 11 18 21 23 22 16  9  2 -3]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
